### ISSUE TITLE
Cannot set docset to one not on list, but with space in name

### ISSUE THREAD

**Issue by jnareb** [jinzhu/zeal-at-point#10]
One cannot set with `M-x zeal-at-point-set-docset` docset to one not present on the list, but with space in the name, like for example "opengl 4", because space triggers item completion.

**Comment by erikstorm** [comment]
I'm also having issues opening the docset for NodeJS. JavaScript seems to work fine, but the NodeJS docs won't open.

**Comment by syohex** [comment]
See #13.

**Comment by jinzhu** [comment]
Thanks for @syohex's PR.
