### ISSUE TITLE
Zeal wasn't found ...

### ISSUE THREAD

**Issue by Derrekito** [jinzhu/zeal-at-point#17]
When I run zeal-at-point I receive the error: 
> zeal wasn't found, install it first...

I do have and use zeal which is installed on my windows machine. Ant idea about how I can fix this?

**Comment by syohex** [comment]
Did you set PATH environment variable correctly ? `(executable-find "zeal")` returns nil on your environment. I suppose zeal is not in PATH directories on your environment.

**Comment by Derrekito** [comment]
Thank you, that corrected the error.
