### ISSUE TITLE
variable zeal-at-point-zeal-version nil when zeal --version output error

### ISSUE THREAD

**Issue by stardiviner** [jinzhu/zeal-at-point#26]
Here is an error which `zeal` caused segementation fault when execute command `zeal --version`.

https://github.com/zealdocs/zeal/issues/595

So might `zeal-at-point` should deprecate this variable.

**Comment by syohex** [comment]
It is your binary issue. zeal-at-point does not work and may crash even if its variable is removed. You should use stable binary.

**Comment by stardiviner** [comment]
The function `zeal-at-point` failed because `zeal-at-point-zeal-version` is nil. If it is remove, then it can temporary solve this problem. Because `Zeal` can start, and query. but just get `segement fault` from command `zeal --version`.

**Comment by syohex** [comment]
It is necessary for old zeal users because old zeal has different interfaces from newer one. And almost users's zeal does not crash by `zeal --version`. You can set `zeal-at-point-zeal-version` manually like `0.3.1` and can avoid this issue.

**Comment by stardiviner** [comment]
You're right, temporary solution is set variable manually. Thanks
