### ISSUE TITLE
zeal-at-point doesn't work with Emacs Lisp docset 

### ISSUE THREAD

**Issue by JAremko** [jinzhu/zeal-at-point#28]
With Emacs lisp `zeal-at-point` shows nothing and the search string is `emacs lisp:let` - _if (let... is at point._ It's probably because Emacs Lisp docset(http://sanfrancisco.kapeli.com/feeds/Emacs_Lisp.tgz ) has white space in the docset folder name.

**Comment by syohex** [comment]
I cannot reproduce.

![zeal-at-point-elisp](https://cloud.githubusercontent.com/assets/554281/19619856/f7a5e9d4-98aa-11e6-8161-0de565cf6b93.gif)

**Comment by JAremko** [comment]
@syohex  It looks like that [my zeal](http://packages.ubuntu.com/xenial/zeal) thinks that the docset should be called `elisp` not `emacs lisp` 

![http://i.imgur.com/0NRGOSh.png?1](http://i.imgur.com/0NRGOSh.png?1)
![http://i.imgur.com/0OZzFR5.png?1](http://i.imgur.com/0OZzFR5.png?1)

**Comment by syohex** [comment]
I use Ubuntu 16.04's zeal(0.2.1-1)

**Comment by Retorz** [comment]
I've also came to the same issue with zeal V0.3.1(installed via PPA), the keyword has changed.

**Comment by lythenas** [comment]
As a temporary fix you could just set the docset prefix of the emacs lisp mode to "elisp"

``` elisp
(add-to-list 'zeal-at-point-mode-alist '(emacs-lisp-mode . "elisp"))
```

**Comment by JAremko** [comment]
@lythenas  it works  but I had to change it a bit(because `zeal-at-point` is lazy):

``` elisp
(advice-add 'zeal-at-point
            :before
            (lambda (x)
              (add-to-list 'zeal-at-point-mode-alist
                           '(emacs-lisp-mode . "elisp"))))
```

**Comment by syohex** [comment]
I have PR(https://github.com/jinzhu/zeal-at-point/pull/29) please review it.
